/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as LeaveIndexRouteImport } from './routes/leave/index'
import { Route as PayrollIndexRouteImport } from './routes/payroll/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as PoliciesPolicyIdRouteImport } from './routes/policies/$policyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIndexRoute = LeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPolicyIdRoute = PoliciesPolicyIdRouteImport.update({
  id: '/policies/$policyId',
  path: '/policies/$policyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/policies/': typeof PoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/attendance': typeof AttendanceIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/leave': typeof LeaveIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/policies': typeof PoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/policies/': typeof PoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/policies/$policyId'
    | '/attendance/'
    | '/employees/'
    | '/inventory/'
    | '/leave/'
    | '/payroll/'
    | '/policies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policies/$policyId'
    | '/attendance'
    | '/employees'
    | '/inventory'
    | '/leave'
    | '/payroll'
    | '/policies'
  id:
    | '__root__'
    | '/'
    | '/policies/$policyId'
    | '/attendance/'
    | '/employees/'
    | '/inventory/'
    | '/leave/'
    | '/payroll/'
    | '/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliciesPolicyIdRoute: typeof PoliciesPolicyIdRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LeaveIndexRoute: typeof LeaveIndexRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/': {
      id: '/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof LeaveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$policyId': {
      id: '/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof PoliciesPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliciesPolicyIdRoute: PoliciesPolicyIdRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LeaveIndexRoute: LeaveIndexRoute,
  PayrollIndexRoute: PayrollIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
