/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as AuditsIndexRouteImport } from './routes/audits/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventoryIdRouteImport } from './routes/inventory/$id'
import { Route as LeaveIndexRouteImport } from './routes/leave/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as PayrollIndexRouteImport } from './routes/payroll/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as PoliciesPolicyIdRouteImport } from './routes/policies/$policyId'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIndexRoute = LeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPolicyIdRoute = PoliciesPolicyIdRouteImport.update({
  id: '/policies/$policyId',
  path: '/policies/$policyId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/audits/': typeof AuditsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/attendance': typeof AttendanceIndexRoute
  '/audits': typeof AuditsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/leave': typeof LeaveIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/audits/': typeof AuditsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inventory/$id'
    | '/policies/$policyId'
    | '/attendance/'
    | '/audits/'
    | '/employees/'
    | '/inventory/'
    | '/leave/'
    | '/messages/'
    | '/payroll/'
    | '/policies/'
    | '/tasks/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/inventory/$id'
    | '/policies/$policyId'
    | '/attendance'
    | '/audits'
    | '/employees'
    | '/inventory'
    | '/leave'
    | '/messages'
    | '/payroll'
    | '/policies'
    | '/tasks'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/inventory/$id'
    | '/policies/$policyId'
    | '/attendance/'
    | '/audits/'
    | '/employees/'
    | '/inventory/'
    | '/leave/'
    | '/messages/'
    | '/payroll/'
    | '/policies/'
    | '/tasks/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  InventoryIdRoute: typeof InventoryIdRoute
  PoliciesPolicyIdRoute: typeof PoliciesPolicyIdRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  AuditsIndexRoute: typeof AuditsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LeaveIndexRoute: typeof LeaveIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/': {
      id: '/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof LeaveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$policyId': {
      id: '/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof PoliciesPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  InventoryIdRoute: InventoryIdRoute,
  PoliciesPolicyIdRoute: PoliciesPolicyIdRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  AuditsIndexRoute: AuditsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LeaveIndexRoute: LeaveIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  PayrollIndexRoute: PayrollIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
